services:
  dev:
    build:
      context: .
      args:
        UID: ${LOCAL_UID:-1000}
        GID: ${LOCAL_GID:-1000}
    environment:
      - DISPLAY=${DISPLAY}
      - LIBGL_ALWAYS_SOFTWARE=${LIBGL_ALWAYS_SOFTWARE:-0}
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - SDL_AUDIODRIVER=${SDL_AUDIODRIVER:-pulse}
    volumes:
      - ./:/workspace:delegated
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native:ro
    working_dir: /workspace
    tty: true
    stdin_open: true
    shm_size: '1gb'
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    command: ["sleep", "infinity"]
